<?php
/**
 * @file
 * cod_registration_reminder.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function cod_registration_reminder_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_reminder_enabled'.
  $field_bases['field_reminder_enabled'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_reminder_enabled',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => '',
        1 => '',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  // Exported field_base: 'field_reminder_interval'.
  $field_bases['field_reminder_interval'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_reminder_interval',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'interval' => array(
        0 => 'interval',
      ),
      'period' => array(
        0 => 'period',
      ),
    ),
    'locked' => 0,
    'module' => 'interval',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'interval',
  );

  return $field_bases;
}
