<?php
// Plugin definition
$plugin = array(
  'title' => t('Aquarius'),
  'icon' => 'aquarius.png',
  'category' => t('COD'),
  'theme' => 'aquarius',
  'css' => '../../../css/panels/aquarius/aquarius.css',
  'regions' => array(
    'primary' => t('Primary'),
    'secondary' => t('Secondary'),
    'tertiary_header' => t('Tertiary header'),
    'tertiary_first' => t('Tertiary First'),
    'tertiary_second' => t('Tertiary Second'),
    'tertiary_third' => t('Tertiary Third'),
    'tertiary_footer' => t('Tertiary Footer'),
    'quaternary' => t('Quaternary'),
    'quinary' => t('Quinary'),
    'senary' => t('Senary'),
    'septenary' => t('Septenary'),
    'octonary' => t('Octonary'),
    'nonary' => t('Nonary'),
    'denary' => t('Denary'),
  ),
);
