<?php
/**
 * @file
 * cod_registration_pages.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function cod_registration_pages_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'panelizer_node:page:default_selection';
  $strongarm->value = 'node:page:default:default';
  $export['panelizer_node:page:default_selection'] = $strongarm;

  return $export;
}
